DROP FUNCTION IF EXISTS apply_tile_action(
  UUID, UUID, TEXT, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER,
  JSONB, JSONB, JSONB, BOOLEAN[], BOOLEAN[], BOOLEAN[], TEXT[]
);

DROP FUNCTION IF EXISTS complete_tile(
  UUID, INTEGER, JSONB, JSONB, INTEGER, JSONB, JSONB, BOOLEAN[], TEXT[]
);

DROP FUNCTION IF EXISTS save_team_state(
  UUID, JSONB, JSONB, INTEGER, JSONB, JSONB, BOOLEAN[], TEXT[]
);

DROP FUNCTION IF EXISTS undo_tile_action(
  UUID, UUID, JSONB, JSONB, INTEGER, JSONB, JSONB, BOOLEAN[], BOOLEAN[], BOOLEAN[], TEXT[], BOOLEAN[], BOOLEAN[], TEXT
);

DROP TABLE IF EXISTS game_actions CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS games CASCADE;
